global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "auth-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["auth-service:3000"]

  - job_name: "ingest-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["ingest-service:3000"]

  - job_name: "library-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["library-service:3000"]

  - job_name: "album-sharing-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["album-sharing-service:3000"]

  - job_name: "search-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["search-service:3000"]

  - job_name: "ml-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["ml-service:8000"]

  - job_name: "worker-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["worker-service:3000"]

  - job_name: "traefik"
    metrics_path: /metrics
    static_configs:
      - targets: ["traefik:8080"]
